#!/bin/bash

GHOSTBUSTER_VERSION='1.1'

set -eu

info() {
  printf "[%s] \033[0;32m%s\033[0m\n" "$(date +%Y-%m-%d_%H-%M-%S)" "$1"
}

error() {
  printf "[%s] \033[0;31m%s\033[0m\n" "$(date +%Y-%m-%d_%H-%M-%S)" "$1"
}

details() {
  printf "[%s] \033[1;33m%s\033[0m\n" "$(date +%Y-%m-%d_%H-%M-%S)" "$1"
}

chat() {
  printf "\033[0;32m%s\033[0m\n" "$1"
}

ask() {
  printf "\033[1;34m%s \033[0m" "$1" 1>&2
  read -r answer
  echo "$answer"
}

if ! command -v twurl &>/dev/null;
then
  if ! command -v ruby &>/dev/null;
  then
    error "Please install ruby:"
    error "  On mac, execute 'brew install ruby'"
    error "  On linux, consult your distros wiki"
    exit 1
  fi
  gem install --user-install -N twurl
fi

twurl="$(ruby -e 'puts Gem.bin_path("twurl", "twurl")')"

if [ ! -f "$HOME/.twurlrc" ];
then
  chat "In order to setup access to the Twitter API, I need some info:"
  API_KEY="$(ask "What is your App API Key:")"
  API_SECRET_KEY="$(ask "What is your App API Secret Key:")"
  chat "Thanks, I will now call the Twitter API to create a user token"
  chat "This will print a link, please open it in the browser where you"
  chat "are logged in to Twitter. The link displays a button 'Authorize"
  chat "App'. Pease click it, immediately afterwards, a PIN will be shown."
  chat "Please copy this PIN, paste it in this terminal and press enter."

  "$twurl" authorize \
    --consumer-key "$API_KEY" \
    --consumer-secret "$API_SECRET_KEY"

  chat "Thanks, I will now start hunting your ghost followers."
fi

followers_file="$(mktemp)"
ghost_file="$(mktemp)"
trap 'rm -f $followers_file $ghost_file' EXIT

while true;
do
  next=""

  info 'Fetching first 100 followers'
  for i in $(seq 1 5);
  do
    url="/1.1/followers/list.json?count=20"
    if [ -n "$next" ];
    then
      url+="&cursor=$next"
    fi
    result="$("$twurl" "$url")"
    next="$(echo "$result" |jq .next_cursor)"
    echo "$result" |jq .users[] >>"$followers_file"
  done

  info 'Extracting ghosts'
  cat "$followers_file" \
    |jq -r '. | select(.followers_count < 10 or .statuses_count <= 1) | .screen_name' \
    |sort -u >"$ghost_file"

  info "Found $(wc -l <"$ghost_file") ghosts"

  for i in $(cat "$ghost_file");
  do 
    user="$("$twurl" -X POST "/1.1/blocks/create.json?screen_name=$i&skip_status=1" |jq -r .screen_name)"
    details "  Blocked user https://twitter.com/$user"
  done

  truncate -s 0 "$followers_file"
  truncate -s 0 "$ghost_file"

  info "Done, sleeping 5 minutes due to API rate limiting"
  info "Press [CTRL]+[C] to exit ghostbuster"
  for i in $(seq 1 5);
  do
    sleep 60
    echo -n '.'
  done
  echo ""
done

# LAST LINE TO DETECT PREVIOUS GHOSTBUSTER
